# Generated by Django 4.2.29 on 2026-03-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработана')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('design', 'UI/UX Design')], max_length=20, verbose_name='Категория')),
                ('badge', models.CharField(max_length=60, verbose_name='Бейдж')),
                ('icon', models.CharField(default='⚡', max_length=10, verbose_name='Иконка (emoji)')),
                ('description', models.TextField(verbose_name='Описание')),
                ('duration', models.CharField(max_length=20, verbose_name='Длительность')),
                ('projects_count', models.PositiveSmallIntegerField(verbose_name='Кол-во проектов')),
                ('level', models.CharField(default='с нуля', max_length=50, verbose_name='Уровень')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена (сом/мес)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('avatar_letter', models.CharField(max_length=2, verbose_name='Буква аватара')),
                ('avatar_color', models.CharField(default='a', max_length=5, verbose_name='Цвет аватара (a/b/c)')),
                ('course_label', models.CharField(max_length=100, verbose_name='Подпись курса')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Рейтинг (1–5)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
    ]
